### ISSUE TITLE
Proton-bridge 1.5.4 dependency on Qt 5.11 too new for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by asoplata** [ProtonMail/proton-bridge#143]
protonbridge 1.5.4 depends on Qt version 5.11, but Ubuntu 18.04 LTS apt repositories only provide up to Qt version 5.9.5 [libqt5core5a](https://packages.ubuntu.com/bionic/libqt5core5a).

## Expected Behavior

Successful execution of `protonmail-bridge`.

## Current Behavior

Running the executable refuses to start:

    $ protonmail-bridge
    protonmail-bridge: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by protonmail-bridge)

## Possible Solution

Either reduce Qt version requirements back to 5.9.5, or recommend user uses `ubuntu-backports` to install a newer Qt version. I have no idea how complicated the former is! But it's all I can think of. I completely understand if it's not feasible.

## Steps to Reproduce

Install the DEB package for protonmail-bridge on Ubuntu 18.04 LTS, then run:

    $ protonmail-bridge

## Version Information

1.5.2 does work correctly, and only 1.5.4 fails this way.

## Context (Environment)

Ubuntu 18.04.5 LTS using the amd64 architecture repositories.

## Detailed Description

After upgrading `proton-bridge` to 1.5.4 using the suggested DEB file `protonmail-bridge_1.5.4-1_amd64.deb` on Ubuntu 18.04 LTS, the install completes without error. Running the executable, however, gives an error indicating that the shared library for Qt Core must be at least version 5.11. Since the latest officially-supported version of Qt Core in Ubuntu 18.04 LTS appears to be 5.9.5 (this package: [libqt5core5a](https://packages.ubuntu.com/bionic/libqt5core5a) ), a standard install of this OS cannot run the new bridge version without relying on `ubuntu-backports` or some other way of updating the library in a non-standard way.

This also means that the DEB install fails silently, since `libqt5core5a` does not satisfy the requirements, and this is not apparent until runtime.

I suspect that this bug may also be an issue for Ubuntu 16.04 (see #141). Ubuntu 18.04 has the package `qml-module-qtquick-controls2` available, but even with the package installed, it still runs into the above issue.

**Comment by ErichRitz** [comment]
Actually the cause of this is that 1.5.2 bundled Qt, but 1.5.4 does not, relying on the system installation of Qt instead.

You can see that the download size for 1.5.4 is much smaller:

```
-rw-r--r-- 1 root root 38M Nov 25 05:11 /var/cache/sbopkg/protonmail-bridge_1.5.2-1_amd64.deb
-rw-r--r-- 1 root root 11M Dec 21 01:40 /var/cache/sbopkg/protonmail-bridge_1.5.4-1_amd64.deb

```

**Comment by dsommers** [comment]
The same issue with RHEL/CentOS/Scientific Linux 7.9.

I installed golang and compiled the `nogui` version without issues, as on this host I don't't need the GUI at all (bridge is started with `--cli`)

**Comment by cuthix** [comment]
There was demand for bridge installation without Qt libs so since 1.5.4 we are not packing Qt libs in rpm packages and we instead realy on system Qt dependecies with minimal version 5.11.3. 

After initial deploy we saw strugle of our users based on older Ubuntu versions (<20.04). Altough we strongly recommend to update to newer version of Ubuntu (>=20.04),  we decided to include Qt libs for deb packages in order to support LTS Ubuntu versions 16.04 and 18.04.  In this moment, deb packages for 1.5.4 includes Qt libs and for users who still have problems we ask to re-download and re-install package:

https://protonmail.com/download/protonmail-bridge_1.5.4-1_amd64.deb

The strategy in near future would be to keep deb packages with Qt libs and rpm packages with system Qt dependecies. If we will have plan to change this decission will inform you in advance.

**Comment by asoplata** [comment]
Thanks! This solved the issue for me, I appreciate it!

**Comment by dsommers** [comment]
Just a generic response to how .deb/.rpm packaging is done.

Building just a single package file for multiple distro versions will fail, as you have noticed.  Especially when having dependencies provided by the host system installing these packages. You should have separate .deb/.rpm packages per supported distribution and distro release (Debian 9, Debian 10, Ubuntu 18.04, Ubuntu 20.04, Ubuntu 20.10, Fedora 32, Fedora 33, RHEL/CentOS 7, RHEL/CentOS 8, and so on).  This will ensure you can have a smaller set of package files and you don't need to pay attention to doing rebuilds of your own PM Bridge packaging each time one of these dependencies you now statically include gets a bug or security fix.

This will of course be more work, as you need to define which distributions and releases you want to support.  And each PM Bridge release means spinning up more build slaves to generate the .deb and .rpm files.  But the result will be less issues related to incompatible dependencies.

Another example of dependencies is the `libstdc++.so` dependency.  The RPM packages provided ny ProtonMail does not work on RHEL/CentOS 7 (which is supported for many years going forward by Red Hat), because the `libstdc++.so` file is lacking symbols the PM Bridge build in the RPM needs.  And you cannot simply upgrade `libstdc++.so` on a host without breaking something else.

A better approach is to get upstream distros to package PM Bridge for you.  There is already an on-going discussion in in ticket #44 for Fedora/EPEL (EPEL meaning RHEL/CentOS).  The downside of this way of packaging is that version rebases does not usually happen in the middle of a distribution release.  For the Ubuntu LTS and RHEL/CentOS releases, that means several years.  What happens in this case is that bug/security fixes gets backported to the package PM Bridge.  This is a well-proven approach to ensure packages and OS is as stable as possible over a longer period of time.

Getting packages upstream distros requires someone to take the lead and to the packaging, getting it through various package reviews and maintain the package for coming releases.  Such a package maintainer can in most cases be anyone being interested in helping out, and it can be more people sharing this task.
