### ISSUE TITLE
'Clear cache' adds extraneous 127.0.0.1 Root CA to macOS System Keychain

### ISSUE THREAD

**Issue by tusing** [ProtonMail/proton-bridge#144]
After using 'clear cache', a 127.0.0.1 root CA is added to the keychain, regardless of whether one is logged into ProtonMail or not, or whether an account even exists.

'clear keychain' does not remove these certificates (#145).

## Expected Behavior

- 127.0.0.1 root CAs should not be added on 'clear cache'
- 'clear keychain' should remove these root CAs

## Current Behavior

Regardless of whether you are logged in or not,

- 'clear cache' adds a 127.0.0.1 root certificate (regardless of whether one already exists)
- 'clear keychain' fails to remove these from the keychain (#145).

https://user-images.githubusercontent.com/1077203/103016104-8b5ebd80-450f-11eb-8a50-3951124995c7.mov

## Version Information

1.5.4

## Context (Environment)

- macOS 10.16 Big Sur
- ProtonMail Bridge 1.5.4
  - Clean install
    - cleared keychain and cache (including 127.0.0.1 root cert from macOS system keychain)
    - logged out
    - removed `~/Library/Caches/ProtonMail Bridge`
  - No accounts added

**Comment by jameshoulahan** [comment]
This is expected behaviour.

The certificate you are seeing is the local certificate used for SSL connections with the bridge's IMAP/SMTP servers. The certificates themselves are stored in bridge's cache. When you select "cleare cache", it clears these certificates, and upon next bridge start, bridge sees that the certificates are missing and thus generates new ones and adds the newly generated ones to the macOS keychain.
