### ISSUE TITLE
SMTP/IMAP with oauth -> is it planned?

### ISSUE THREAD

**Issue by JambonBeurreVodka** [ProtonMail/proton-bridge#183]
The only feature that protonmail lacks is SMTP/IMAP support with oauth, like Gmail / yahoo mail do. On my macbook I go to internet accounts > add email and I have a popup to login on the gmail website and they check my phone number. 

Why I need this feature? I want to be able to use any email client on the phone. And I don't like the idea to depend on the protonmail bridge to make it work with third-party email clients on my macbook. 

Do you plan to support this feature? If no, is there a technical reason? It seems that only the big companies support it. Middle-sized privacy-focused email providers don't support oauth with SMTP/IMAP as far as I know.

**Comment by ErichRitz** [comment]
Please read these articles so you can convince yourself what you ask for is not possible:

https://protonmail.com/blog/protonmail-threat-model/
https://protonmail.com/blog/what-is-end-to-end-encryption/
https://protonmail.com/blog/zero-access-encryption/
https://protonmail.com/blog/encrypted_email_authentication/

In summary: ProtonMail does not have your plaintext emails.  They only have data which is the GPG-encrypted form of your email.  They also don't have access to your private GPG key.  Any email client interacting with the ProtonMail servers must handle the GPG encryption/decryption.  This is what the Bridge, mobile, and web clients do.

Also this is the wrong place to ask for such a feature.  This is the github repo for Bridge, and you're asking for a feature to be added to the ProtonMail servers so that you don't have to use Bridge.

**Comment by andrzejsza** [comment]
As @ErichRitz said, IMAP/SMTP protocols don't have capability of handling pgg. The password needed to decrypt the messages is only accessible to Bridge and decryption must be done separately.
