### ISSUE TITLE
Can't move Bridge window under plasma-wayland DE

### ISSUE THREAD

**Issue by mattiaverga** [ProtonMail/proton-bridge#193]
Running Fedora 34 with KDE/plasma-wayland, when Bridge window is opened I cannot move it across the screen, it's locked on opening coordinates.

I can see some warnings in the log, but I don't know if they're related:
```
time="Apr 28 18:15:29.868" level=warning msg="qrc:/ProtonUI/BugReportWindow.qml:218:9: QML Row: Cannot specify left, right, horizontalCenter, fill or centerIn anchors for items inside Row. Row will not function." pkg=frontend/qml
time="Apr 28 18:15:29.959" level=warning msg="qrc:/BridgeUI/DialogKeychainChange.qml:35:5: QML Connections: Cannot assign to non-existent property \"onValueChanged\"" pkg=frontend/qml
time="Apr 28 18:15:29.976" level=warning msg="GraphicsInfo of WindowTitleBar_QMLTYPE_29(0x3e02b70) api 2 majorVersion 2 minorVersion 0 profile 0 renderableType 0 shaderCompilationType 1 shaderSourceType 3 shaderType 1" pkg=frontend/qml
time="Apr 28 18:15:29.981" level=warning msg="Wayland does not support QWindow::requestActivate()" pkg=frontend/qml
time="Apr 28 18:15:29.981" level=warning msg="qrc:/BridgeUI/DialogKeychainChange.qml:36:9: Unable to assign QString to QObject*" pkg=frontend/qml
```

## Expected Behavior
I would expect to be able to move the Bridge window app wherever I want.

## Current Behavior
Windows i locked on opening coordinates.

## Version Information
Bridge v1.6.9

**Comment by Ammako** [comment]
I see these errors in my log too, aside from the Wayland one. I can move the Bridge window, but it's extremely buggy. Jumps all over the screen while dragging the window around, if I'm unfortunate enough to let go of the mouse button at the wrong time the window could even end up off-screen.

Xfce though, so GTK and X11. Might be different running a Qt app in a GTK environment like Xfce, vs running it in a pure Qt environment like KDE. No idea if the issues are related because the error message are cryptic enough for me.

**Comment by mattiaverga** [comment]
Bridge 2.1.0 now works quite well in plasma-wayland, so closing this issue.
