### ISSUE TITLE
Unknown charset

### ISSUE THREAD

**Issue by chiraag-nataraj** [ProtonMail/proton-bridge#202]
After the recent release of the 4.0 webapp, it seems that I am running into this issue with the bridge:
`cannot list messages (false, 28356:28362, [RFC822.SIZE]): list message build: unknown charset: unknown charset: message: unhandled charset "iso-8859-1"  pkg=imap`
`cannot list messages (false, 17419, [RFC822.HEADER]): list message build: unknown charset: unknown charset: message: unhandled charset "iso-8859-1"  pkg=imap`

I am using `fetchmail` to download emails, which has worked until now without too many issues.

**Comment by chiraag-nataraj** [comment]
Seems to have been resolved by logging out and back in again

**Comment by chiraag-nataraj** [comment]
Sorry, logging out and back in allowed me to download _some_ emails, but I'm running into the error again.

**Comment by jameshoulahan** [comment]
Thanks for the report.

We have received a couple reports through customer support over the past ~week about this issue but it's still unclear exactly why this is happening. I'm glad you reported this here because you can probably help us debug this on a more technical level than is usually possible via customer support.

Messages inside the proton "ecosystem" should all be UTF-8; any incoming/imported messages should be re-encoded as UTF-8 (unless they're already encrypted/signed upon arrival). Somehow, though, a few messages have been sneaking through over the past week that have non-UTF-8 encodings.

It would be very helpful if you could provide us with the raw headers of the message that is causing the problem. You could figure out which message is the culprit by manually forcing bridge to build each message individually and seeing which message leads to the error.

Try something like this:
- telnet into bridge: `telnet localhost 1143`
- login: `tag login yourEmailAddress@pm.me yourBridgePassword`
- select the mailbox (probably inbox): `tag select inbox`
- we know the offending message is in seqnum range 28356:28362 (based on your original post -- maybe this is no longer true if you cleared bridge cache) so try to build each message in that range:
  - `tag fetch 28356 (BODY.PEEK[])`
  - `tag fetch 28357 (BODY.PEEK[])`
  - ...
  - `tag fetch 28362 (BODY.PEEK[])`
- for the message that eventually fails to build, see what its subject is (here assume 28356): `tag fetch 1 (BODY.PEEK[HEADER.FIELDS (Subject)])`

Once you have the subject, go to webapp, find the offending message, and select `View headers` and let us know what the `Content-Type` of the message is there.

If you could do that, it would be really helpful! Thanks in advance.

**Comment by chiraag-nataraj** [comment]
So if I try to run the last bit (`tag fetch 17 (BODY.PEEK[HEADER.FIELDS (Subject)])`), it comes up with `tag NO list message build: unknown charset: unknown charset: message: unhandled charset "iso-8859-1"`.

**Comment by chiraag-nataraj** [comment]
Okay, so I narrowed it down to one message. I've attached the full headers
[here](https://github.com/ProtonMail/proton-bridge/files/6624755/pgp.txt).

**Comment by chiraag-nataraj** [comment]
If I mark that message as 'read' (so `fetchmail` doesn't try to download it), all other messages download successfully.

**Comment by jameshoulahan** [comment]
Damn, sorry for misleading you, I assumed off the top of my head that fetching the header fields alone wouldn't require a full build of the message -- should've actually checked before replying! 🤦 

Awesome that you got the headers though, this is really helpful. I'll let you know when there's an update.

**Comment by dmtucker** [comment]
Hitting this or a very similar error too (even after logging out and back in). Haven't been able to find the right log with the error, tho (it shows up as an OS notification).

**Comment by dickolsson** [comment]
I am getting this exact error as well. I am trying to narrow it down to a specific message in order to do more debugging. I'll come back with a comment if/when I find something.

**Comment by jameshoulahan** [comment]
Hi all, thanks for the help. Just letting you know, we've fixed the issue and it will be available via an early-access update to v1.8.7 in the next day or so.
