### ISSUE TITLE
[MacOS] Add an option to remove ProtonMail Bridge icon in menu bar

### ISSUE THREAD

**Issue by mlbiche** [ProtonMail/proton-bridge#21]
The Proton Bridge icon is always displayed in the MacOS system menu bar. It would be great to have an option in Proton Bridge settings to hide it.

**Comment by exander77** [comment]
@mlbiche In which menu bar? Do you mean tray icon?

**Comment by mlbiche** [comment]
@exander77 I am talking about the MacOS system menu bar. This icon :

![ProtonMail Bridge icon in MacOS menu bar](https://framapic.org/gMr0YAp9dzzt/nHgGEsIjI9gJ.png)

**Comment by exander77** [comment]
@mlbiche Oh, I understand. ProtonMail could do something about it, but in reality, it is an OS issue. They seem to forget about it in Apple and did introduce ability to hide these icons as is normal on Windows and Linux. Somebody wrote a tool for that: https://github.com/Mortennn/Dozer

**Comment by mlbiche** [comment]
@exander77 Thank you for this tip ! 🎉

**Comment by andrzejsza** [comment]
agreed with @exander77 that it should be the OS handling this. from ProtonMail point of view, the icon is desired.

**Comment by deltakroneker** [comment]
@exander77 @andrzejsza 

I see your point about OS not allowing to just drag-and-remove third party app icons from the menu bar, but that doesn't mean this feature shouldn't be implemented.
I believe this should be a quality-of-life enhancement that Proton can introduce, as **many** of other apps do even though your before-mentioned problem exists.

Example: 1Password offers this functionality as part of their settings, which doesn't quit the process, just removes the menu bar icon.
![Screen Shot 2023-02-23 at 17 00 51](https://user-images.githubusercontent.com/26824971/220962353-17bb5b71-debf-46fb-a8c3-383092edb315.png)

Also many other apps do, which allows you to declutter your menu bar even with that Apple's constraint.
The point is even stronger by the actual use case of the Bridge app, menu icon just does not provide **any** additional shortcuts for user interaction, it's just a display item which for many users is just unnecessary since you don't use the bridge, you use the mail clients that bridge connects to.

Anyways I am not aware of the development timeline or the priorities in the bridge, but I see this as a wanted feature nonetheless.

**Comment by junk1tm** [comment]
Even if it is the OS fault, it shouldn't affect the users of your app.

As @deltakroneker already mentioned, many macOS apps do provide an option to hide their menu bar icons, as it is a basic QoL feature, and so should do ProtonMail Bridge.

@exander77 @andrzejsza please consider reopening the issue.

**Comment by exander77** [comment]
@deltakroneker @junk1tm If it is a basic QoL feature as you claim, your OS producer should provide it. Have you opened an issue with your OS producer? If your OS producer is unresponsive to your request, such feature my go against the philosophy of your OS and as such ProtonMail should not interfere.

It can be done on the application level, but that creates tonne of duplicating functionality, not to mention fragmented UI configuration. Both Windows and Linux provides this functionality, so this is really up to your OS producer.

**Comment by exander77** [comment]
Also, now there seems to be free (collapse)/paid (hide) app that does this and emulates Windows functionality on MacOS:
https://www.macupdate.com/app/mac/59344/vanilla

**Comment by alkusin** [comment]
I know this issue was closed and you don't seem wanting to work on it, but I ask too: please add this option.

I have 7 apps that originally sit in menu bar, ProtonMail Bridge is **the only one** impossible to hide. It is, for me and some other people, quite useless to have it permanently in this area, if needed we can open its window simply from apps launcher/folder.
And, no, I don't want to install a third-party program to hide only one icon.

Maybe you don't know macOS enough or you simply don't like it, that's ok, but it shouldn't penalize users, and  some of us pay for your service. Adding this little feature shouldn't be too much of a hassle, as a lot of devs include it in their programs.

**Comment by steebchen** [comment]
Agreed, I'd like to ask to re-consider this. Of course ideally this would be solved universally, but it isn't, and for me similar others ProtonMail is the only thing showing constantly in the menu bar while all other apps (which are 5+) have an option to hide the menu item.
