### ISSUE TITLE
Is ProtonMail staff reading this issue tracker at all?

### ISSUE THREAD

**Issue by sirius-c** [ProtonMail/proton-bridge#23]
Judging from the activity so far, it does not seem that any comment/acknowledgement/question came from ProtonMail staff.

It would be good to know if they do read, and if there is actually any point in reporting issues here, or if this is supposed to be just a community forum.

How is this issue tracker supposed to be used in relation to the 'Report a bug' feature of the Bridge?

**Comment by jameshoulahan** [comment]
We can assure you that we will read and respond to all issues reported here. As interaction with the open source community is new to our team, we wanted to wait until the end of our sprint to discuss how best to allocate our limited time to doing this. But you can rest assured that every issue here will be addressed.

Issues reported here should be of a more technical nature, ideally with some initial insight into a potential root cause. Otherwise, please use "Report a bug".

**Comment by sirius-c** [comment]
Thanks for clarifying. This will be the second issue closed. I hope for efficient further bug elimination.
