### ISSUE TITLE
Text is too small in Wayland HiDPI environment

### ISSUE THREAD

**Issue by emilio** [ProtonMail/proton-bridge#254]
Just updated the protonmail bridge, and the new version has too small text / layout.

## Expected Behavior

Text is sized normally.

## Current Behavior

Text is too small.

## Possible Solution

```
$ QT_QPA_PLATFORM=wayland /home/emilio/.cache/protonmail/bridge/updates/2.1.0/proton-bridge
```

displays as expected. Not sure whether that can easily be enabled by default or not.

## Steps to Reproduce

1. Open the bridge.
2. No step two :)

## Version Information

2.1.0

## Context (Environment)

This is a pretty standard GNOME Wayland environment, on Fedora, with 200% scaling on the monitor.

**Comment by HansVanpee** [comment]
Same problem on X11 with HiDPI monitor.

**Comment by davidlick** [comment]
Same problem. It seems that the bridge is not respecting the scaling settings in Wayland.

OS: Fedora
DE: GNOME Wayland
HW: Dell XPS 15 9500
Resolution: 3840x2400 Scaling 200%
Bridge version: v2.1.3

**Comment by andrzejsza** [comment]
are you still experiencing issues with v3?

**Comment by HansVanpee** [comment]
Sorry for my late reply. The problem is solved with the latest version: text and icons are adapted to the screen resolution.

Thanks for the update!

Kind regards,

​Hans Vanpée

[vanpee.fr - développement informatique](https://vanpee.fr)

Tél: [06 24 04 06 73](tel:+33962547082)

Mail: ***@***.******@***.***)

Web: vanpee.fr

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
