### ISSUE TITLE
question about source-code for Import-Export app

### ISSUE THREAD

**Issue by jokeyrhyme** [ProtonMail/proton-bridge#261]
Howdie, thanks for doing so much development work out in the open, and thanks for providing the Import-Export app, which is working well for me

I wanted to double-check: the [README.md](https://github.com/ProtonMail/proton-bridge/blob/master/README.md#description-import-export-app) says:

> The Import-Export app is developed in separate branch `master-ie`.

And I can browse the branches for this repository: https://github.com/ProtonMail/proton-bridge/branches

But there does not seem to be a `master-ie` branch

Has development been moved to a different repository? Is the website and README.md out of date?

Cheers! <3

**Comment by andrzejsza** [comment]
hi there. so the truth is that the I-E app has been separated from the main repo when we've gone out with Bridge V2 (https://github.com/ProtonMail/proton-bridge/blob/master/Changelog.md - look for [Bridge 2.0.0] Kwai). 
there were no change to the I-E app since [IE 1.3.2] Farg.
we are planning a bigger refactor of the I-E app in the upcoming months and were hoping to publish the rewritten code then in a separate repo.
I hope that makes sense.

**Comment by molaeiali** [comment]
@andrzejsza So I cannot update this package https://aur.archlinux.org/packages/protonmail-import-export-app from 2.1.1? I don't see a 1.3.2 branch

**Comment by andrzejsza** [comment]
yes, you cannot. but there is nothing to update since 1.3.2.

**Comment by molaeiali** [comment]
> yes, you cannot. but there is nothing to update since 1.3.2.

I meant 1.2.2 to 1.3.2, was written the version incorrect

So it means than from version 1.2.2 to 1.3.2 is not open-source? Or is it just not tagged? Isn't it possible to tag it? Or point me to a commit? Thanks

**Comment by andrzejsza** [comment]
it wasn't tagged... https://github.com/ProtonMail/proton-bridge/tree/ie-1.3.2
but again - big rewrite is coming, so I wouldn't worry about it in the meantime.

**Comment by andrzejsza** [comment]
I'll close for now. you will hear when the rewrite is done 👍

**Comment by keywordnew** [comment]
The Import-Export app for ProtonMail in `brew` is marked as "deprecated".

This thread above (#261) cited in https://github.com/Homebrew/homebrew-cask/pull/139755 as the reason. A search of Releases finds no mention of the Import-Export app since Dec 2021. 

Is the designation "deprecated" by reason of the app being "discontinued" accurate enough to keep?

See:
- https://formulae.brew.sh/cask/protonmail-import-export
- https://github.com/Homebrew/homebrew-cask/blob/2e05509707d6950cb6042480cf5a6b87b6af8b0c/Casks/p/protonmail-import-export.rb#L10
