### ISSUE TITLE
Transparent GUI Window Ubuntu 22.04

### ISSUE THREAD

**Issue by 0n0n0m0uz** [ProtonMail/proton-bridge#264]
I recently updated to Ubuntu 22.04 and protonmail bridge window is completely transparent.  I have tried uninstalling and the same.  I would imagine some of the changes in Ubuntu version may be the culprit.

**Comment by MelReynolds** [comment]
I am experiencing this as well. The original issue report is obviously low quality, so I will try to provide some additional information:

**### Expected Behavior**
Protonmail Bridge launches with GUI visible in window frame.

### **Current Behavior**
Protonmail Bridge launches with GUI transparent (background wallpaper visible) in window frame.

### **Possible Solution**
Add native Wayland support? 
### 
**Steps to Reproduce**

Launch Protonmail Bridge with Wayland Windowing System. NOTE! The bridge functions (i.e. I can send and receive emails via Thunderbird, I just can’t access the GUI, because the window is transparent withing the frame) 

### **Version Information**
2.1.3 (Was also present in previous versions.)

### **Context (Environment)**

Fedora 36 Workstation 64-bit
Gnome 42 DE
Wayland DE (APP WORKS AS EXPECTED UNDER XORG!)
Nvidia Display Driver 510.68.02 (present over multiple driver releases)

I'll be following this report as a test to see if Proton is actually monitoring and responding to issues. My impression is that for unclear reasons Proton support for Linux is very subpar... Yes, Linux is 2%. If Proton doesn't wish to support Linux, please state that you do not wish to support Linux.

**Comment by andrzejsza** [comment]
hi @MelReynolds, thanks for the report. of course we're monitoring, even if are not that great with responding 😅
we (the Bridge team) actually spend by far more time on Linux than any other platform but do acknowledge our shortcomings here (from binaries distribution to GUI). We're hoping to give it even more time in the future.

For this particular issue, the problem seems to be somewhat related to NVIDIA GPU. We've got the same report on Fedora 36, also on nvidia.

**Comment by MelReynolds** [comment]
Thank you @andrzejsza. I got carried away at the end of the issue report. I apologize for being an entitled jerk. I'll work to do better. I believe in Proton's mission and appreciate your work.

**Comment by MelReynolds** [comment]
Installed the Nvidia 515 driver from rpmfusion this morning. This Nvidia driver appears to completely resolve this issue - Bridge GUI is now visible and interactive in window frame. I consider this issue resolved.

Please rest assured that if I encounter even the slightest inconvenience in the future I'll report back and likely complain relentlessly. :neckbeard:

**Comment by Blookebleep** [comment]
I second this issue.
I'm using:
GNOME: 42.2
Wayland
Nvidia Driver: 515.57

Also received this transparent looking window using Wayland which was not a problem using XORG. Seems that this may not have Wayland support or is not falling back too a XORG session using Wayland. Although, I have not tested this on an AMD GPU which has notoriously better driver support. Non-apparent in the Proton VPN application.

No real reason for me to say this here but I just wanna add that this issue seems to be constant.

**Comment by jeremy-lilly** [comment]
I have this issue as well. I'm using:

Arch Linux
Kernel 5.18.11
GNOME 42.2
Wayland
Nvidia 515.57
Proton Bridge Flatpak from Flathub

Interestingly, I have a very similar problem using Zoom. This seems like an electron/nvidia/wayland issue.

**Comment by BezPowell** [comment]
Also seeing this on Fedora Silverblue 36 with propriety nvidia drivers using the Bridge flatpak. Annoying, as it's about the only software application that doesn't work on Wayland now for me.

**Comment by bentenjamin** [comment]
+1

OS: Fedora release 36 (Thirty Six) x86_64 
Host: OMEN by HP Laptop 15-ce0xx 
Kernel: 5.19.8-200.fc36.x86_64 
Uptime: 51 mins 
Packages: 3405 (rpm), 53 (flatpak) 
Shell: fish 3.5.0 
Resolution: 1920x1080 
DE: GNOME 42.4 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1060 Mobile 6GB 
Memory: 6439MiB / 15944MiB

```
WARN[Sep 14 17:50:23.175] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.  pkg=frontent/qml
WARN[Sep 14 17:50:24.480] qglx_findConfig: Failed to finding matching FBConfig (8 8 8 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.480] qglx_findConfig: Failed to finding matching FBConfig (1 8 8 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.481] qglx_findConfig: Failed to finding matching FBConfig (1 1 8 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.482] qglx_findConfig: Failed to finding matching FBConfig (1 1 1 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.483] qglx_findConfig: Failed to finding matching FBConfig (1 1 1 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.484] qglx_findConfig: Failed to finding matching FBConfig (1 1 1 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.511] qglx_findConfig: Failed to finding matching FBConfig (8 8 8 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.512] qglx_findConfig: Failed to finding matching FBConfig (1 8 8 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.513] qglx_findConfig: Failed to finding matching FBConfig (1 1 8 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.513] qglx_findConfig: Failed to finding matching FBConfig (1 1 1 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.514] qglx_findConfig: Failed to finding matching FBConfig (1 1 1 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.516] qglx_findConfig: Failed to finding matching FBConfig (1 1 1 8)  pkg=frontent/qml
WARN[Sep 14 17:50:24.557] QSGContext::initialize: depth buffer support missing, expect rendering errors  pkg=frontent/qml
```

**Comment by haflaxa** [comment]
## +1 

`OS`: **Fedora 36 (x86_64)**
`DE`: **GNOME 42.5**

`WM`: **Mutter**
`WM Theme`: **Adwaita**

`GPU`: **NVIDIA**
`NVIDIA Driver Version`: **515.65.01**

**Comment by andrzejsza** [comment]
could you guys try with 2.4.0 (beta) and confirm if that's still a problem?

**Comment by MelReynolds** [comment]
> could you guys try with 2.4.0 (beta) and confirm if that's still a problem?

Yes, this fixes this issue for me! Thank you.
