### ISSUE TITLE
ProtonBridge does not allows a non-paid account to login, despite a paid account has already logged in.

### ISSUE THREAD

**Issue by turbothinh** [ProtonMail/proton-bridge#288]
## Expected Behavior
ProtonBridge should be available for a non-paid account if a paid account is logged in already.

## Current Behavior
I logged in already with a paid account, then try to login to a 2nd account, which is not a paid account but not possible/

## Version Information
2.2.2 on Mac

## Context (Environment)
I think the app should be available as long as the user logged in with one paid account. Bridge enables proton mail to connect to email clients like Thunderbird, Apple Mail which makes it more convenient for the user. This feature would be very helpful for us who don't want to use my primary mail for everything on the internet.

## Possible Implementation
When the user login, check if there are any paid accounts has already logged in. If no paid account has logged in and the current account is not a paid account, show the error.

**Comment by andrzejsza** [comment]
Yes, this is expected behaviour and no, we won't be changing this for now. We understand this use case (1 user has both paid and non-paid accounts) but this would require quite a bit of engineering (for instance, all of the non-paid accounts would need to be automatically logged out when the paid account is logged out).
Why not just have multiple addresses on the main, paid account?
