### ISSUE TITLE
pass manager: Use Proton-specific sub-folder

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#31]
# Summary

When using the [pass password manager](https://www.passwordstore.org/), ProtonMail Bridge should initialize in a sub-folder specific to itself

# Background

Before I used ProtonMail Bridge, I used `pass` to manage my passwords. Now, ProtonMail Bridge commits passwords to my existing password store. This is fine, but I also synchronize my `pass` repository to a remote repository. I end up pushing my ProtonMail Bridge commits up to my password repository. It causes problems when I use ProtonMail Bridge on two different machines.

# Details

`pass` can be initialized in a sub-folder:

```sh
pass init --path=sub-folder gpg-id
```

There could be a ProtonMail Bridge-specific folder that doesn't interfere with existing personal passwords I manage with `pass`.

# Outcome

ProtonMail Bridge password credentials do not interfere with user's personal password repositories

**Comment by jwflory** [comment]
For a short-term fix, I created `~/.password-store/.gitignore` with the following contents:

```gitignore
# Do not commit ProtonMail passwords into `pass` because they are dynamic and
# change on every specific system. So, avoid it by not committing it.

protonmail-credentials
```

This seems to have fixed it for me, but I need to test on more systems first to confirm.

**Comment by quicquid** [comment]
It took me months until I realized that proton-mail actually does use pass. I had regularly deleted the additional passwords and wondered where they were coming from.

**Comment by JPUnD** [comment]
I would also like to support this feature.

However I had pass on a custom directory and on trying to run `protonmail-bridge` for the first time I had the error:
```
no keychain management installed on this system
```

I realized that `protonmail-bridge` doesn't take into account the env variables that I set in my `.zshrc` using `export PASSWORD_STORE_DIR="/my/custom/dir"` which means that you could just use the non default location for your `pass` password storage and then `protonmail-bridge` would initialize it's credentials in the default location under `~/.password-store`.

Because I don't mind having it all under the same folder I ended up symlinking `~/.password-store` with `/my/custom/dir` and that fixed the previous issue I had.

While not ideal it's a possible workaround, just like the one using the `.gitignore`.

**Comment by andrzejsza** [comment]
good news is that #77 is now fixed. as for this request, it might require more changes in the keychain library that we use and so we won't be looking into this at this stage.
