### ISSUE TITLE
On Startup: Bridge opens up, how to just have it in tray?

### ISSUE THREAD

**Issue by ReaderGuy42** [ProtonMail/proton-bridge#319]
Up until a few days ago, Bridge started at startup of my Linux Mint PC, and it lived happily in the tray. Now it seems that at startup Bridge still starts as well, but now it also opens the window.

## Expected Behavior
Start Bridge ONLY in tray

## Current Behavior
Bridge opens window on startup

## Possible Solution
change settings?

## Steps to Reproduce

1. start PC
2. have Bridge set to start on boot
3. Bridge starts
4. Bridge opens window
5.

## Version Information

2.30
## Context (Environment)

It isn't a big deal, it's just a little annoying to always have to click the window away.

## Detailed Description

I'd just like a setting so that it goes back to just starting in the tray

Thanks :)

**Comment by gabor-meszaros** [comment]
Hi @ReaderGuy42, Thank you for taking the time to report this problem. Our GitHub issues are for problems that require deeper technical discussions/investigations. If your Bridge Version is 2.3.0, and it has just broken recently, please contact customer support. If your Bridge version is 3.0.6, then it is indeed a bug in the first beta release, and will be solved soon (Internal reference: GODT-2051).

**Comment by ReaderGuy42** [comment]
All right thank you :) But 2.3.0 is still the latest "stable" release?

**Comment by gabor-meszaros** [comment]
Yes, 2.3.0 is the latest stable release, 3.0.6 is the current beta release. You do not necessarily get the option to update to it because we roll it out progressively.

**Comment by ReaderGuy42** [comment]
OK, perfect, I don't need the beta yet. Thanks for the advice, I've sent support a message.

**Comment by morciej** [comment]
FYI, beta version 3.0.9 resolves the issue, because it correctly accepts a --no-window parameter. Previous versions required `-no-window` (SINGLE dash, inconsistent with `--no-window` that goes into Autostart, and Linux practice). BTW the `no-window` parameter in either form is not documented in `protonmail-bridge --help`.

What worked for me as a temporary workaround was to have a command `protonmail-bridge -no-window`, created under a new different name such as `temp-pm-bridge-fix` in the Autostart, while disabling Autostart option in the Bridge UI. If you just edit the original Autostart command in place, Bridge will revert it at the next opportunity. :smile:
