### ISSUE TITLE
Mailspring Email Client Support

### ISSUE THREAD

**Issue by 1cg** [ProtonMail/proton-bridge#33]
Mailspring is a modern email client that is available on all the major platforms, including Linux.  Currently it does not work with the Bridge.  Quite a lot of research has gone into it on this bug:

https://github.com/Foundry376/Mailspring/issues/429

The crux of the issue (from what I can tell) appears to be unquoted string literals in some responses, which breaks the Mailcore2 library.  Therefore fixing this issue should open up a broader set of project to work with the bridge.

**Comment by jameshoulahan** [comment]
Going forward, we certainly do want to improve the experience of using more mail clients with bridge. And I agree with you, Mailspring is a wonderful mail client; I myself am a fan.

You are correct that the crux of (one of) the issue(s) relates to quoted literals. We have an internal build of bridge which replies with everything quoted (except INBOX) and this build seems to play quite nicely with Mailspring. However, I wouldn't yet say the experience with this build is "great". For example, Mailspring constantly tries to create folders where ProtonMail doesn't allow it to, which means snooze functionality is broken. Also, Mailspring seems to have quite a lot of internal state which sometimes means it trusts its own internal state more than bridge; moving a message in a way which is disallowed by bridge is still reflected by Mailspring, and even restarting it doesn't retrigger a refetch of the messages in the Mailbox (it effectively gets permanently out of sync).

All this is to say: we are getting there, but aren't quite there yet. However, it's getting closer!

**Comment by chg20** [comment]
Thanks James, great to hear you are working on it and have a much better understanding of the issue than I do!  :+1: I'll mention it on the other thread.

**Comment by exander77** [comment]
@chg20 
I was looking into MailSpring myself. And it seems to be an error on their end.
1. They do not comply with RFC and require quoting (of things that do not need to be quoted).
2. The write into Mailspring/Snooze folder you cannot configure.
3. The actual mailsync part is not even opensource, otherwise, it would be easily fixable by the community.

I would not even recommend using it, as the part which is important is actually closed source and you have no idea what is it doing: https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md#why-is-mailsync-closed-source
Also, info there seems to be total bollocks... it is not OpenSource as it would be hard to build? Odds of PR low?

You can review their issues here: https://github.com/Foundry376/Mailspring
Most relevant here: https://github.com/Foundry376/Mailspring/issues/429

**Comment by chg20** [comment]
I see your point @exander77 but right now it is the most reasonably modern mail client available on linux.  We can hope that Protonmail decides to write an electron app, or perhaps Airmail will port their app to electron, but right now Mailspring is the best.

**Comment by exander77** [comment]
@chg20 There is an unofficial Electron Base application EletronMail: https://github.com/vladimiry/ElectronMail

It has an offline store of the messages with search feature and the store is fully encrypted.

**Comment by exander77** [comment]
@chg20 I wonder how you measure it is the "best" as they can't fix this since 2017 and you blame ProtonMail.

**Comment by chg20** [comment]
@exander77 we are all just trying to get through it, brother

software is hard and i appreciate what both protonmail and mailspring are trying to do

**Comment by anjoweichbrodt** [comment]
Many thanks for creating such a great product!
I really hope that compatibility with Mailspring will be reached soon. It is really needed.

**Comment by C0DK** [comment]
Lack of Mailspring is my main reason for not buying your product, sadly.. Hope to see an update

**Comment by ploum** [comment]
AFAIK, this has been fixed on Mailspring side.

**Comment by ploum** [comment]
bug can be closed : https://github.com/Foundry376/Mailspring/pull/2323
