### ISSUE TITLE
MIME `multipart/alternative` messages have plaintext parts stripped

### ISSUE THREAD

**Issue by duncancmt** [ProtonMail/proton-bridge#340]
## Expected Behavior

`multipart/alternative` messages should be passed through unchanged. However, only the HTML part makes it through. My mail shouldn't be getting mangled while it passes through protonmail's services.

## Current Behavior

In a multipart message, only the HTML alternative makes it through.

## Possible Solution

Stop mangling email.

## Steps to Reproduce

Send a multipart message with a `text/plain` part and a `text/html` part. Observe that the received message is not a MIME `multipart/alternative` and contains only the `text/html` portion.

## Version Information
v2.3.0

**Comment by LBeernaertProton** [comment]
Hey @duncancmt, could you try and see if you can still reproduce this issue on v3?

**Comment by jameshoulahan** [comment]
For now, this is a limitation of the Proton API: messages can only have one body. This means that whenever we are presented with a `multipart/alternative` (both when sending outgoing messages and when receiving incoming messages), we need to pick which of the alternatives to store as the encrypted message body.

The preferred solution to this is completing a long-delayed migration so that we can have multiple message contents attached to a message. This will enable both versioning of drafts and preserving multipart alternative. But until that is done, we will unfortunately be required to pick just one of the alternative parts.

As this is not directly a Bridge issue, I will close this.

**Comment by duncancmt** [comment]
> The preferred solution to this is completing a long-delayed migration

Could you point me at something that tracks the progress of this migration? Do you have any idea when this might release?

**Comment by jameshoulahan** [comment]
This is an internal data model migration. We host a very large number of messages and it will likely take a few months at minimum.

**Comment by jkraemer** [comment]
Just ran into this. What's the status on your migration?
