### ISSUE TITLE
Protonmail Bridge not running on MacOS Ventura 13.3

### ISSUE THREAD

**Issue by sergio1468** [ProtonMail/proton-bridge#376]
I recently installed MacOS Ventura (13.3) on my Macbook Pro (late 2013) using OPENCORE. The MacOS runs smoothly. However, since then, Protonmail Bridge software is not able to run anymore. 

Normally Protonmail Bridge app should open to allow configuration of the Apple Mail client with the Protonmail account. 

When I start Protonmail Bridge, a empty grey window opens, instead of the usual window with all menus inside. that's all. 

I have no Idea what geos wrong. 

## Steps to Reproduce

1.
2.
3.
4.

I'm using the last version of Protonmail Bridge, version 3.0.21

I cannot configure my proton mail account on the Apple mail client anymore. 

I don't know what to do.

**Comment by LBeernaertProton** [comment]
@sergio1468 According to https://support.apple.com/en-us/HT213264, your machine is not officially supported with Ventura. You have an unsupported/unofficial setup,  there is clearly a hardware incompatibility issue and we can't help you with this. 

You can try the 3.1 pre-release build which defaults to software rendering, it might *may* fix your problem.

**Comment by sergio1468** [comment]
Thanks!

Serge Abramowski

**Comment by h3x4d3x4** [comment]
I'm having the same issue but with a small difference. I was running Proton Mail Bridge on my 2015 Macbook Pro just fine even using OCLP with Ventura. A few days ago decided to spoof the SMBIOS to a Macbook Pro 2017 to use Universal Control cause the 2015 model is blacklisted. All went smooth except that Proton Mail Bridge doesn't open anymore, and it's the only app with this issue. I know this issue is totally due to my Macbook running Ventura and me spoofing the SMBIOS but any help would be very much appreciated as it's the only app that has this issue from dozens of apps installed.

**Comment by sergio1468** [comment]
Hey folks,

Problem solved automatically with last security update of Ventura 13.3.1

Cheers

Serge Abramowski

**Comment by sergio1468** [comment]
Problem solved automatically with last security update of Ventura 13.3.1

Cheers

Serge Abramowski

**Comment by h3x4d3x4** [comment]
Yeah, i didn't have any issue on 13.3.1 already, it just happened after i spoofed the SMBIOS to a 2017 Macbook Pro in order to us UC. :( 

Currently using CLI until i find a solution but it's most certainly related to graphics.
