### ISSUE TITLE
Transparent Settings window

### ISSUE THREAD

**Issue by kstev99** [ProtonMail/proton-bridge#382]
I'm trying to install proton-bridge 3.0.21on my older laptop for an upcoming trip.   I install it and it brings up a hollow shell for a settings screen and I am unable to change any settings.  I have uninstalled and re-installed several times, same result

**Comment by kstev99** [comment]
Windows 10

**Comment by andrzejsza** [comment]
hi. we believe this to be fixed with the recent beta https://github.com/ProtonMail/proton-bridge/releases/tag/v3.1.1 - we've switched the default GUI rendering from hardware to software, which was causing problem on some setups. If the issue persist, please contact support, as we would need more details for debugging.
