### ISSUE TITLE
Unexplicable error - "wsasend: An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by tinmanjk** [ProtonMail/proton-bridge#383]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Current Behavior

Receiving the following error in the Proton Bridge CLI (confirmed in logs)
time="May  5 09:26:27.541" level=error msg="IMAP server error" error="write tcp 127.0.0.1:1143->127.0.0.1:3721: wsasend: An existing connection was forcibly closed by the remote host."

## Steps to Reproduce

1. 
2.
3.
4.

## Version Information

Proton Mail Bridge 3.1.2 for Windows
## Context (Environment)

1143 is the port for IMAP., not sure what 127.0.0.1:3721 is.
I was receiving this error a lot before turning ESET Antivirus' Firewall into Learning mode which is supposed to create rules for new connections and not block connections.

**Comment by LBeernaertProton** [comment]
hey @tinmanjk , that is not an "unexplicable error". That happens when your IMAP client terminates its connection to the IMAP server (Bridge) before Bridge can send back the full reply.

The `3271` is the port assigned to your client connection after connecting to  the server (Bridge). You can read more about it here https://en.wikipedia.org/wiki/Transmission_Control_Protocol.
