### ISSUE TITLE
[Linux] Flatpak distribution: Proposal to co-maintain

### ISSUE THREAD

**Issue by A6GibKm** [ProtonMail/proton-bridge#72]
I maintain a [Flatpak](https://flatpak.org/) distribution for ProtonMail Bridge at [flathub/ch.protonmail.protonmail-bridge](https://github.com/flathub/ch.protonmail.protonmail-bridge). I would like to extend an invitation to the developers upstream to maintain or co-maintain this repository, now or whenever this aligns with your plans and resources, just drop by and I can contact the Flathub administrators.

The general idea of Flathub is that maintainers themselves (can) maintain their application and provide direct updates to end-user to various, if not most,  Linux distributions in a reproducible way.

- This does not need any bandwidth nor build time from ProtonMail, which are provided by [Flathub.org](https://flathub.org/home)
- Even if the app repository is at the [Flathub](https://github.com/flathub) organisation, app maintainers get admin rights to the app repository.

Advantages:

- Allows for automatic updates
- Application is fully sandboxed
- distro-agnostic
- Full control over dependencies

What's currently missing:

- Provide a Flatpak built from source instead of using the [.deb](https://protonmail.com/bridge/install) file. This depends on #16 and #47.
- Provide application metainfo #71

**Note:** I already opened an internal issue in the past and received its corresponding reply. The goal here is to keep the invitation open in the future and allow community discussion.

**Comment by cuthix** [comment]
Hi,
 first of all: thanks for patience and I would like to ask for more.
We are very happy that you took your time to share our app with others.
Unfortunately, right now we are not able to participate much in distribution
and maintaining of this project. The Bridge and the Import-Export app are the
first apps of Proton which are distributed on linux, but more apps are planned.
Therefore, we now have discussion across the teams, what should be our global
approach to it. Especially in terms of security of our users. This is not just
involving maintaining the package itself, but also do security audits and
checks of dependencies.

I can't promise any time from our side to get us back to you. We will try to
put underlying issues to our backlog so the package creation and distribution
is more transparent. Once we will have decision I will get back to you.

Cheers,
Jakub and the rest of Bridge team

**Comment by AJCxZ0** [comment]
@cuthix,
As a user of the ProtonMail Bridge flatpak [Thank you, @A6GibKm], I strongly encourage the Proton team to focus on Flatpak as the platform-agnostic packaging for the software rather than trying to cater to some small fraction of the many Linux platforms and versions while failing to provide all the infrastructure necessary to enable us to properly and securely maintain these packages on our systems (i.e. well-maintained repositories for each Linux platform and supported version). It is an order of magnitude less work to do this the right way and you have a free offer of assistance.

Having an application phone home to find out if there is a newer version then notify the user through a GUI is not an appropriate method of managing software on Linux platforms, even if it is accepted on some other platforms (with the ongoing decades of history of harm from doing so being a sad matter of record).

Please understand that _we are already using the Flatpak_ since it is the only properly maintained source and are therefore already completely trusting @A6GibKm to package the software which we run on our systems.

**Comment by cuthix** [comment]
Hi again,
after discussion within other products we decided to not support flatpak, hence I will close this issue. We might reconsider this in future and if so we will inform you. Right now our priority is to create deb and rpm repositories common for all proton products.

Nevertheless, I opened internal issue (GODT-975) with these tasks:
* create tgz with vendor sources in CI
* add package metadata: .desktop, .plist, .aip
* add more build instructions about install from source

Even though we are not officially support flatpak we will try to make your life easier.

**Comment by A6GibKm** [comment]
Thanks for the reply, it is perfectly understandable. 

On the other hand having vendor sources in the tarball would indeed make life way better for packagers, not just flatpak, so it is great news.

**Comment by cassidyjames** [comment]
@cuthix apologies if this is not the proper place for this conversation, but since it's been a few years and a lot has changed, I wanted to check back in on Proton's decision on Flatpak.

- **Steam Deck** is in the hands of millions of users, and ships **Flathub as its desktop app store**

- Linux desktops and distros across the ecosystem like Endless OS, Fedora, Linux Mint, Manjaro, CentOS, AlmaLinux, Clear Linux, elementary OS, PureOS, Zorin OS, MX Linux, KDE Neon, and Pop!_OS all **ship Flatpak out of the box**, with **Flathub by default** or enabled with two clicks

- Flatpak is **built on cross-desktop technologies you're already using** that are standardized across all major Linux distros; **FreeDesktop APIs and Portals are what make apps work on Linux** without monumental per-distro efforts—things like autostarting, cross-desktop dark style, and even just the app icon showing up in your app launcher are all FreeDesktop specs. The folks building the distros listed above as well as Ubuntu, GNOME, KDE, Red Hat, Flatpak, Flathub, and Snap are all working together on these APIs! Continuing to ensure the app uses these standard APIs will not only make the Flatpak work better across desktops, it will make the app work more consistently regardless of how it’s packaged and distributed.

As far as user interest:

- Proton Mail Bridge has **[over 68k installs](https://flathub.org/apps/ch.protonmail.protonmail-bridge) from Flathub**

- Proton VPN has **[over 138k installs](https://flathub.org/apps/com.protonvpn.www) from Flathub**

Full disclosure, I'm employed by the non-profit Endless OS Foundation; we help bridge the digital divide by providing and contributing to open technologies—one of which is [Flathub](https://flathub.org/), the independent and most widely-used app store for Linux.

I also contribute to Flathub personally because I want to see it grow and remain recognized as the best place to get apps for Linux. **It makes the app experience so much better for Linux users**—which in turn makes the entire Linux platform better.

If following up over email is more appropriate, I'm always available over at cassidy@endlessos.org. Flatpak contributors also have an [active Matrix channel](https://matrix.to/#/#flatpak:matrix.org) if that's preferred!

I'd love to chat and help get the Proton apps verified on Flathub. Thanks for your time. 😄

**Comment by julianfairfax** [comment]
@cuthix it has been almost 3 years since you closed this issue. Many of us would like Proton to look into it again (https://github.com/ProtonMail/proton-bridge/issues/420). Is that something you could help with?

**Comment by LBeernaertProton** [comment]
**Disclaimer: Personal opinion.** - I would love to see an official flatpak release of bridge and I'm trying to promote the this to the team.

That being said, there are things are a couple of major things that we need to address first before we can, hopefully, dedicate time to this.

**Comment by gabor-meszaros** [comment]
Thanks @cassidyjames for your offer. Flatpak package support is a request that has come up frequently in the past few months. It is definitely on our radar, and we will look into it in the future. Having said that, it is currently not on our short-term plans. Providing official Flatpak support requires changes in our QA, customer support, and build infrastructure. At the current stage, we rely on the help of the community to provide Flatpak packages. Although it is not on our short-term plans, we are very open to help our community to make it happen. If you have time to work on it, we can talk over email to know if there are any blocking problems that we can help to resolve. My email address is firstname.lastname at proton dot ch.

**Comment by AJCxZ0** [comment]
@gabor-meszaros and @LBeernaertProton, I'm sure that all we Flatpak users appreciate your advocacy Proton's ongoing consideration. Reading my comment from three years ago, the only thing which has changed is the significant focus on Flatpak as the de facto package distribution format for Linux platforms* for application developers.

One recent illustrative example is the Thunderbird project taking over [org.mozilla.Thunderbird](https://flathub.org/apps/org.mozilla.Thunderbird) and targeting Flatpak to provide the official, supported and up-to-date releases instead of the various application versions packaged on many different platforms with different policies by different people on different schedules. See also [Firefox](https://flathub.org/apps/org.mozilla.firefox), [GIMP](https://flathub.org/apps/org.gimp.GIMP), [Telegram](https://flathub.org/apps/org.telegram.desktop), [OBS Studio](https://flathub.org/apps/com.obsproject.Studio), (almost?) all GNOME and KDE applications and rest of the ~772~ ~773~ 774 [verified Flatpaks](https://flathub.org/apps/collection/verified).

While your relationship with @A6GibKm is none of my business and no-one has invited me to negotiate, a free lifetime [Proton Family](https://proton.me/family) or [Business](https://proton.me/business/plans) subscription and suitable channels for upstream collaboration would seem like a good start, especially with the cost-saving which will come from you not wasting time developing and maintaining the wrong way to distribute software to Linux platforms - a fraction of which can be spent ensuring that @A6GibKm is not alone in maintaining the Flatpak (for your, their and our benefit).

You also get a [✓Verified checkmark](https://flathub.org/about) which actually means something important to us and to you.


*[There are and always will be native packages and cross-platform alternatives including snap, appimage, etc., however application developers should start with Flatpak and then consider which others to provide and/or support.]

**Comment by baarkerlounger** [comment]
> there are things are a couple of major things that we need to address first before we can, hopefully, dedicate time to this.

@LBeernaertProton as it's been a little of a year since this comment I wondered if either of those things might have been addressed now, or if you might have any more information as to what would need to happen to make this possible?
