### ISSUE TITLE
Import/Export Tool - missing All Mail target folder

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#73]
I have tried staring migration, but I am unsure where to migrate emails from All Mail folder on ma Gmail, as All Mail is missing in the menu for ProtonMail.

**Comment by horejsek** [comment]
All Mail is special mailbox. It's not folder but label which is the view over all messages from all folders. Every message has to be in some folder, system one or custom one. That's why All Mail is not a target option. You can create custom folder for All Mail from Gmail if needed.

**Comment by exander77** [comment]
@horejsek We already discussed this elsewhere. E-mail can be in All Mail only. Why is this being here again?

**Comment by horejsek** [comment]
Please, read in the quote: `We want to avoid it`. Meaning: there are currently valid paths how to move message to All Mail only (and thus it's not a bug per se), but it's something we don't want to allow and we are working on disabling this option from all edge cases.

**Comment by exander77** [comment]
@horejsek I am aware. And when you do it, I will leave this service. In the meantime, I am requesting that may email is sorted as I see fit.

> Every message has to be in some folder, system one or custom one.

Also, this statement is false, regardless of what you want.

**Comment by skooda** [comment]
Protonmail tries to shorten the path for users to the secure email, and also to offer an UX that will suit most of them. Therefore, in order to achieve this, it is sometimes necessary to make a product decision. Of course, all these decisions do not always satisfies everyone, but we are strives to make it simple for most users.

That's why **All** Mail contains **all** messages. Also from our perspective All Mail is rather considered Label than a Folder, because message cannot be in two folders at the same time.

Also the rule that Every message should be in some folder (to be concrete, it should be in exactly one folder), is a product decision. It doesn't mean that it's already true for actual version, because this is something we are already working on, but it is the rule which we follow on our path to make UX simple.

**Comment by exander77** [comment]
@skooda You mean UX that reports than any operations succeeded regardless of the actual result?

I disagree with the statement. ProtonMail often selects decisions that are against industry standards and well behaved behaviour.

I am not at all concerned All Mail is a folder or a label or any other semantics you want to choose. But it is normal for emails to only in All Mail. And it is normal for Trash and Spam not to be in All Mail. It is a generally accepted solution and people are familiar with it. Both Gmail and Outlook use it the same way.

> Also the rule that Every message should be in some folder (to be concrete, it should be in exactly one folder), is a product decision. It doesn't mean that it's already true for actual version, because this is something we are already working on, but it is the rule which we follow on our path to make UX simple.

I can agree with this, make folder called Rest, and put all emails which are not in any other folder in that folder. (That would also fix current situation.) And all emails put in the All Mail which are not present in any folder would be there. The remove Trash and Spam from All Mail folder and we are good to go. This is not so hard.

**Comment by skooda** [comment]
Making such a product decision requires more than just doing the same as the competition.

Sometimes we are blocked with technical possibilities of given problem, sometimes the problem is related to other functions of the application or to behavior of our web application. It is also necessary to think about the intelligibility of the UX.

We think it's okay if the label called *ALL MAIL**contains **all mail**.

I am sorry that this solution does not suit you, but we also have users who like it and understand it.

Maybe at some point in future we'll find there is enough of users who would appreciate some switch to hide trash and spam messages from all mail, but at the moment this is not a product priority and there is no plan to do so.

**Comment by exander77** [comment]
@skooda This is not about what suits me, but the operating in this fashion breaks mail clients as was already reported...
