### ISSUE TITLE
[Question] Import-Export: Link for latest release

### ISSUE THREAD

**Issue by A6GibKm** [ProtonMail/proton-bridge#74]
Is there anywhere where I can find the latest version number, for say the .deb, package of the Import-Export App?

Currently protonmail-bridge has https://protonmail.com/download/current_version_linux.json.

EDIT: I need a way to automatically fetch the version, https://protonmail.com/import-export does not help for this use-case as the version does not appear with `curl`.

EDIT n2: What I am actually looking for is the version `x.y.z-w` of the deb package.

**Comment by jameshoulahan** [comment]
This is what you are looking for: https://protonmail.com/download/current_version_ie_linux.json

(at the time of writing there is an inconsistency between the `Version` field and the x.y.z-w in the deb/rpm files due to an issue some users experienced when upgrading from pre-stable to stable Import-Export versions; I expect you can ignore this for your use-case)

**Comment by A6GibKm** [comment]
Yes, this is precisely what I needed. Thanks.

**Comment by A6GibKm** [comment]
I would like to ask again for this info due to the latest url change to proton.me. Are the links 

- https://protonmail.com/download/current_version_ie_linux.json
- https://protonmail.com/download/current_version_linux.json

going to keep working in the future? Do they need to update their urls pointing to protonmail.com?
