### ISSUE TITLE
Advice how to build with local version of libraries

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#9]
Hello, I am now trying to build with latest version of go-mime and gopenpgp to look into some issues. What is the recommended way to build against local version?

I have tried:
```
  github.com/ProtonMail/gopenpgp => ../gopenpgp
  github.com/ProtonMail/go-mime => ../go-mime
```
But it leads me to:
```
../gopenpgp/crypto/message.go:15:2: use of internal package github.com/ProtonMail/gopenpgp/v2/internal not allowed
```

**Comment by kortschak** [comment]
This is a result of injudicious use of replace directives in the original source. You can get around this horrible practice by making all the downstream module deps available locally. In order to do this, I needed to have two copies of github.com/ProtonMail/gopenpgp, one checked out at v2 (put in a `../opengpgp/v2` directory and the other checked out at `d398098` (obtainable from the pseudo version in the go.mod file from this repo). To complete the build fixing, I also needed to add a replace in the gopenpgp (v1 version) go.mod `replace golang.org/x/crypto => ../crypto` and check out the github.com/ProtonMail/go-mime at `09454e3` (placed in the appropriate location).

Reproducible builds with Go modules are not meant to be this difficult.

**Comment by exander77** [comment]
Thank you, will try that!

**Comment by cuthix** [comment]
Updating to the latest gopenpgp is planned (internal reference GODT-296). We will let you know

**Comment by exander77** [comment]
@cuthix This is not about new gopengp so much as about the ability to build with local libraries.

**Comment by horejsek** [comment]
Ah, I see. In that case @kortschak already provided answer for your question. Note you need to check out locally the same versions as we refer to in go.mod. There is new version of gopenpgp (the latest one, v2) which is not compatible and we are working on updating from v1.
