### ISSUE TITLE
Import-Export tool (probably ProtonBridge as well) destroys some Subjects

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#90]
## Expected Behavior
Subjects should not be modified.

## Current Behavior
Some subjects are modified.

## Possible Solution
Do not modify any subjects.

## Steps to Reproduce
Import email with following subjects:
empty string
missing
Hodnocení zakoupeného zboží

They are transformed into "(No Subject)".

**Comment by jameshoulahan** [comment]
Thanks for the report.

This is done server-side, neither by bridge nor by import export. If the subject is missing, we simply upload it missing to the server.

Regarding the subject `Hodnocení zakoupeného zboží`, this is most likely a latin2 encoded subject which was probably stripped by the old parser. As handling of foreign-encodings has been rewritten, I'd be interested to see how the new parser behaves here.

You can confirm that neither bridge nor import export adds `(No Subject)` by grepping the repository for the string `(No Subject)`.

I kindly request you to contact protonmail (not bridge) support with this issue so that it is forwarded to the appropriate team.

**Comment by exander77** [comment]
Also replaces new lines with spaces.

**Comment by exander77** [comment]
It actually seems like \s+ is replaced with space.
